kind: pipeline
type: docker
name: vue-builder


steps:
  # 建立 npm 環境 
  # echo -n "${DRONE_COMMIT_SHA},latest" > .tags  把 tag 丟進去 tags 檔案內，一次可以更新自定義內的所有版號 ex: latest
  - name: build-npm
    image: node:14.16.0-slim
    commands:
      - echo "step in npm install .........."
      - npm install
      - echo "step in build project .........."
      - npm run build
      - ls -al
      - echo -n "${DRONE_COMMIT_SHA},latest" > .tags
      - ls -al
      - cat .tags
    when:
      branch:
      - master
      - develop

  # build 自己的 image
  # ${DRONE_REPO_NAME} ===> 使用變數控制 (參考 :https://docs.drone.io/pipeline/environment/reference/)

  - name: build-image
    image: plugins/docker
    settings:
      username: 
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: giorann4056/${DRONE_REPO_NAME} 
    when:
      branch:
      - master
      - develop


trigger:
  branch:
  - master
  - develop
  event:
  - push